---
name: Run Tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.0
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: run-tests
    steps:
      - name: Check out code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
      - name: Set execute permission on deploy.sh
        run: chmod +x deploy.sh
      - name: Deploy
        run: sh ./deploy.sh

        
